const BAD_REQUEST = 400;
const AUTHORIZATION_ERROR = 401;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST,
  AUTHORIZATION_ERROR,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
};
